name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'Ethical Hacking/**'
      - '_resources/**'

jobs:
  markdown-to-pdf:
    name: Convert Markdown to PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Convert Markdown to PDF
        uses: docker://pandoc/latex:2.9
        with:
          args: >
            --resource-path=.:./Ethical\ Hacking:./_resources
            $(find Ethical\ Hacking -name '*.md' -exec printf "'{}' " \;)
            -o EthicalHacking.pdf

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: EthicalHacking.pdf
          path: EthicalHacking.pdf
