name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'Ethical Hacking/**'
      - '_resources/**'

jobs:
  markdown-to-pdf:
    name: Convert Markdown to PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pandoc
        run: sudo apt-get install pandoc texlive texlive-xetex texlive-latex-extra

      - name: Convert Markdown to PDF
        run: |
          pandoc $(find 'Ethical Hacking' -name '*.md' -exec printf "'{}' " \;) -o EthicalHacking.pdf --resource-path='.':'_resources' --pdf-engine=xelatex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: EthicalHacking.pdf
          path: EthicalHacking.pdf
